### ISSUE TITLE
opcache:optimize error logs

### ISSUE THREAD

**Issue by dorin-niscu** [appstract/laravel-opcache#75] opened 2018-10-03 14:57 UTC
Laravel 5.7
PHP 7.2

I am calling **Artisan::call('opcache:optimize');**

It works fine excepting the error logs.

```
[2018-10-02 20:51:37] local.ERROR: Cannot declare class Composer\Autoload\ClassLoader, because the name is already in use {"exception":"[object] (Symfony\\Component\\Debug\\Exception\\FatalErrorException(code: 1): Cannot declare class Composer\\Autoload\\ClassLoader, because the name is already in use at /home/vagrant/Code/laravel/vendor/composer/composer/src/Composer/Autoload/ClassLoader.php:43)
[stacktrace]
#0 /home/vagrant/Code/laravel/vendor/laravel/framework/src/Illuminate/Foundation/Bootstrap/HandleExceptions.php(137): Symfony\\Component\\Debug\\Exception\\FatalErrorException->__construct()
#1 /home/vagrant/Code/laravel/vendor/laravel/framework/src/Illuminate/Foundation/Bootstrap/HandleExceptions.php(123): Illuminate\\Foundation\\Bootstrap\\HandleExceptions->fatalExceptionFromError()
#2 /home/vagrant/Code/laravel/vendor/laravel/framework/src/Illuminate/Foundation/Bootstrap/HandleExceptions.php(0): Illuminate\\Foundation\\Bootstrap\\HandleExceptions->handleShutdown()
#3 {main}
"} 
```

**Comment by mpyw** [comment] 2019-02-05 13:02
Confirmed. +1 👍

**Comment by mpyw** [comment] 2019-02-05 13:13
`vendor/composer/composer/src/Composer/Autoload/ClassLoader.php`

seems to be copied to

`vendor/composer/ClassLoader.php`.

We must get rid of this duplication.

**Comment by ovanschie** [comment] 2019-06-22 22:09
Fixed in new version

**Closed by ovanschie** 2019-06-22 22:09 UTC
Labels: bug
