### ISSUE TITLE
Only variable references should be returned by reference

### ISSUE THREAD

**Issue by orumad** [appstract/laravel-opcache#11] opened 2017-02-28 09:52 UTC
When I try any `opcache` command  (`config`, `clear`, `status`) from `laravel-opcache`, I get:

```
[ErrorException]
  Only variable references should be returned by reference
```

I've tested this in my **local environment (macOS, Valet, PHP7.1, OPCache, Laravel 5.4, etc.)** and in the **production environment (Debian 8, Nginx, PHP7.0, OPCache, Laravel 5.4)**.

**Comment by ovanschie** [comment] 2017-02-28 10:24
The error message is caused by another package of us, please run composer update to update that package. The error message should be fixed, but I don't know if it fixes the issue. Give it a try.

**Comment by ovanschie** [comment] 2017-03-06 19:16
This should be fixed, so we are closing this issue.

Re open it if you feel the need :)

**Closed by ovanschie** 2017-03-06 19:16 UTC
